export const GET_WEATHER = 'GET_WEATHER';
export const SET_FORECAST = 'SET_FORECAST';
export const SET_WEATHER = 'SET_WEATHER';

export const SET_LOCATION = 'SET_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
